# Generated by Django 4.0.4 on 2022-05-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psia_python_app', '0004_remove_imagepost_image_userpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='psia_python_app/templates/psia_python_app/static/images'),
        ),
    ]
