# Generated by Django 4.0.4 on 2022-05-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psia_python_app', '0005_alter_userpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
