# Generated by Django 4.0.4 on 2022-05-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psia_python_app', '0007_userpost_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='profile_image',
        ),
    ]
